steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        echo "**********************************"
        echo "$BRANCH NAME"
        echo "**********************************"
    env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

  - id: 'tf-init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        terraform init
    env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

  - id: 'tf-plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        terraform plan
    env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

  - id: 'tf-apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        if [["$BRANCH_NAME" == "prod"]]; then
        echo "branch name is prod, executing terraform apply"
        terraform apply --auto-approve
        exit 0
        else
        echo "branch name is not prod, skipping terraform apply"
        exit 0
        fi
    env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
  #
