steps:
  - name: 'bash'
    args: ['echo', 'Hello world!']
  logsBucket: 'gs://tt-cicdbuild-bucket'
  serviceAccount: 'projects/balmy-atom-445612-h4/serviceAccounts/25094830000@cloudbuild.gserviceaccount.com'
  options:
    logging: CLOUD_LOGGING_ONLY

  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        echo "**********************************"
        echo "$BRANCH NAME"
        echo "**********************************"

  - id: 'tf-init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        terraform init

  - id: 'tf-plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        terraform plan

  - id: 'tf-apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        if [["$BRANCH_NAME" == "prod"]]; then
        echo "branch name is prod, executing terraform apply"
        terraform apply --auto-approve
        exit 0
        else
        echo "branch name is not prod, skipping terraform apply"
        exit 0
        fi
  #
